version: '3.3'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: api
    restart: always
    volumes:
      - ./:/app
    ports:
      - 8001:8001
    networks: 
      - unkids

networks:
  unkids:
    external: true