version: "3.3"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
